# Generated by Django 4.2.4 on 2023-09-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('permanent_address', models.CharField(max_length=500, null=True)),
                ('current_address', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(default='Nepal', max_length=50)),
                ('message', models.TextField(null=True)),
                ('cv', models.FileField(null=True, upload_to='cv_uploads/')),
                ('pp_photo', models.FileField(null=True, upload_to='pp_photo')),
                ('scan_passport', models.FileField(null=True, upload_to='passport')),
                ('academic_certificate', models.FileField(null=True, upload_to='academic_certificate')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('mobile', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(max_length=100)),
                ('SiteContact', models.CharField(max_length=100)),
                ('SiteEmail', models.EmailField(max_length=254)),
                ('SiteAddress', models.CharField(max_length=500)),
                ('Sitedescription', models.CharField(max_length=500)),
                ('Sitelicence', models.CharField(max_length=300)),
                ('SiteRegister', models.CharField(max_length=100, null=True)),
                ('Sitetwitterlink', models.CharField(max_length=300)),
                ('Sitefacebooklink', models.CharField(max_length=300)),
                ('Sitelinkdinlink', models.CharField(max_length=300)),
                ('Siteinstagram', models.CharField(max_length=300)),
                ('Siteyoutubelink', models.CharField(max_length=300)),
                ('logo', models.ImageField(default=None, max_length=200, null=True, upload_to='Global/')),
                ('back_image', models.ImageField(null=True, upload_to='Global/')),
                ('brochure', models.FileField(null=True, upload_to='brochure/')),
                ('broc_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=50)),
                ('position', models.IntegerField()),
                ('page_type', models.CharField(blank=True, choices=[('Home', 'Home'), ('Home/Slider', 'Home/Slider'), ('Home/Aboutus', 'Home/Aboutus'), ('legaldocument', 'legaldocument'), ('legaldocument/slider', 'legaldocument/slider'), ('Organization chart', 'Organization chart'), ('Current Demand', 'Current Demand'), ('Current Demand/slider', 'Current Demand/slider'), ('Newspaper Vacancy', 'Newspaper Vacancy'), ('NewspaperVacancy/Slider', 'NewspaperVacancy/Slider'), ('Apply/Slider', 'Apply/Slider'), ('M&V/Slider', 'M&V/Slider'), ('Mission & Vision', 'Mission & Vision'), ('Testimonial', 'Testimonial'), ('Clients', 'Clients'), ('AboutUs', 'AboutUs'), ('About Nepal', 'About Nepal'), ('About Nepal/Image', 'About Nepal/Image'), ('Message from MD', 'Message from MD'), ('Recruitment Process', 'Recruitment Process'), ('Why Choose Us', 'Why Choose Us'), ('WhyChooseUs/slider', 'WhyChooseUs/slider'), ('Job Sector', 'Job Sector'), ('Job Sector/slider', 'Job Sector/slider'), ('Documentation', 'Documentation'), ('Documentation/Country', 'Documentation/Country'), ('Gallery', 'Gallery'), ('Gallery/slider', 'Gallery/slider'), ('Gallery/Company profile', 'Gallery/Company profile'), ('Gallery/Events', 'Gallery/Events'), ('Contact us', 'contact us')], max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField(null=True)),
                ('desc', models.TextField(null=True)),
                ('bannerimage', models.ImageField(null=True, upload_to='banner/')),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keyword', models.CharField(max_length=100, null=True)),
                ('icon_image', models.ImageField(null=True, upload_to='icon/')),
                ('slider_image', models.ImageField(null=True, upload_to='slider/')),
                ('brochure', models.FileField(null=True, upload_to='brochure/')),
                ('back_image', models.ImageField(null=True, upload_to='background/')),
                ('published_date', models.CharField(max_length=50, null=True)),
                ('interview_date', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='adminpanel.navigation')),
            ],
        ),
    ]
