# Generated by Django 4.2.4 on 2023-09-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_academic_certificate_apply_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Home/Slider', 'Home/Slider'), ('Home/Aboutus', 'Home/Aboutus'), ('legaldocument', 'legaldocument'), ('legaldocument/slider', 'legaldocument/slider'), ('Organization chart', 'Organization chart'), ('Current Demand', 'Current Demand'), ('Current Demand/slider', 'Current Demand/slider'), ('Newspaper Vacancy', 'Newspaper Vacancy'), ('NewspaperVacancy/Slider', 'NewspaperVacancy/Slider'), ('Apply/Slider', 'Apply/Slider'), ('M&V/Slider', 'M&V/Slider'), ('Mission & Vision', 'Mission & Vision'), ('Testimonial', 'Testimonial'), ('Clients', 'Clients'), ('AboutUs', 'AboutUs'), ('About Nepal', 'About Nepal'), ('About Nepal/Image', 'About Nepal/Image'), ('Message from MD', 'Message from MD'), ('Recruitment Process', 'Recruitment Process'), ('Why Choose Us/right', 'Why Choose Us/right'), ('Why Choose Us/left', 'Why Choose Us/left'), ('WhyChooseUs/slider', 'WhyChooseUs/slider'), ('Job Sector', 'Job Sector'), ('Job Sector/slider', 'Job Sector/slider'), ('Documentation', 'Documentation'), ('Documentation/Country', 'Documentation/Country'), ('Gallery', 'Gallery'), ('Gallery/slider', 'Gallery/slider'), ('Gallery/Company profile', 'Gallery/Company profile'), ('Gallery/Events', 'Gallery/Events'), ('Contact us', 'contact us')], max_length=50, null=True),
        ),
    ]
